# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IcoDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico_name', models.CharField(default='', max_length=255, verbose_name='项目名称')),
                ('token', models.CharField(default='', max_length=255, verbose_name='项目token代号')),
                ('price', models.CharField(default='', max_length=255, verbose_name='公募成本价')),
                ('country', models.CharField(default='', max_length=255, verbose_name='国家')),
                ('country_cn', models.CharField(default='', max_length=255, verbose_name='国家中文名字')),
                ('tokens', models.CharField(default='', max_length=255, verbose_name='代币总量')),
                ('token_type', models.CharField(default='', max_length=255, verbose_name='代币类型')),
                ('hardcap', models.CharField(default='', max_length=255, verbose_name='硬上限')),
                ('softcap', models.CharField(default='', max_length=255, verbose_name='软上限')),
                ('raised', models.CharField(default='', max_length=255, verbose_name='募集金额(usd)')),
                ('platform', models.CharField(default='', max_length=255, verbose_name='平台')),
                ('distributed', models.CharField(default='', max_length=255, verbose_name='公募百分比')),
                ('ico_start', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='ico开始时间')),
                ('ico_end', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='ico结束时间')),
                ('category', models.CharField(default='', max_length=255, verbose_name='分类目录')),
                ('url', models.CharField(default='', max_length=255, verbose_name='官网地址')),
                ('tagline', models.CharField(default='', max_length=255, verbose_name='简介')),
                ('intro', models.TextField(default='', verbose_name='介绍')),
                ('intro_cn', models.TextField(default='', verbose_name='中文介绍')),
                ('registration', models.CharField(default='', max_length=255, verbose_name='注册类型')),
                ('status', models.CharField(default='', max_length=255, verbose_name='项目状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'db_table': 'ico_data',
                'verbose_name': 'ico数据表',
                'managed': True,
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
