# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0002_icoexchangesstatsmodel_icogithubstatsmodel_icosocialmediamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcoStatsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico_name', models.CharField(default='', max_length=255, verbose_name='项目名称')),
                ('token', models.CharField(default='', max_length=255, verbose_name='项目代号')),
                ('category', models.CharField(default='', max_length=255, verbose_name='类别（可挖不可挖矿平台币应用币）')),
                ('first_block_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='第一个区块生成时间')),
                ('ico_price', models.CharField(default='', max_length=255, verbose_name='ico价格')),
                ('total_volumn', models.BigIntegerField(default=0, verbose_name='币总量')),
                ('maximum_tps', models.CharField(default='', max_length=255, verbose_name='最大每秒传输量')),
                ('transactions_number', models.BigIntegerField(default=0, max_length=255, verbose_name='当日总交易次数')),
                ('total_transactions_fees', models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='当日总交易费')),
                ('avg_transactions_value', models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='交易价值均值')),
                ('meidan_transactions_value', models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='交易价值中位数')),
                ('total_output_value', models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='当日总交易传出量')),
                ('assets_turnover_rate', models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='资产中转率')),
                ('actual_tps', models.BigIntegerField(default=0, verbose_name='实际每秒交易量')),
                ('tps_utilization_rate', models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='tps利用率')),
                ('median_confirmation_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='确认时间中位数')),
                ('mempool_size', models.BigIntegerField(default=0, verbose_name='未确认交易数量')),
                ('current_best_transaction_fees', models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='最佳交易费用')),
                ('blocks_last_24h', models.BigIntegerField(default=0, verbose_name='24小时生成区块数')),
                ('blocks_avg_perhour', models.BigIntegerField(default=0, verbose_name='每小时生成区块数')),
                ('reward_last_24h', models.BigIntegerField(default=0, verbose_name='24小时产生奖励数')),
                ('top_100_richest', models.BigIntegerField(default=0, verbose_name='前100占有币情况')),
                ('wealth_distribution_top10', models.BigIntegerField(default=0, verbose_name='财富10')),
                ('wealth_distribution_top100', models.BigIntegerField(default=0, verbose_name='财富100')),
                ('wealth_distribution_top1000', models.BigIntegerField(default=0, verbose_name='财富1000')),
                ('wealth_distribution_top10000', models.BigIntegerField(default=0, verbose_name='财富10000')),
                ('address_richer_than_1usd', models.BigIntegerField(default=0, verbose_name='金额超过1usd地址')),
                ('address_richer_than_100usd', models.BigIntegerField(default=0, verbose_name='金额超过100usd地址')),
                ('address_richer_than_1000usd', models.BigIntegerField(default=0, verbose_name='金额超过1000usd地址')),
                ('address_richer_than_10000usd', models.BigIntegerField(default=0, verbose_name='金额超过10000usd地址')),
                ('active_addresses_last24h', models.BigIntegerField(default=0, verbose_name='过去24小时活跃地址数')),
                ('new_addresses_last24h', models.BigIntegerField(default=0, verbose_name='过去24小时新建地址数')),
                ('transaction_largest100', models.BigIntegerField(default=0, verbose_name='24小时最大100笔交易')),
                ('address_numbers', models.BigIntegerField(default=0, verbose_name='持币地址数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'verbose_name': 'ico指标表',
                'abstract': False,
                'managed': True,
                'db_table': 'ico_stats',
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
