# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0003_icostatsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icostatsmodel',
            name='transactions_number',
            field=models.BigIntegerField(default=0, verbose_name='当日总交易次数'),
        ),
    ]
