# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0004_auto_20180508_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icostatsmodel',
            old_name='transactions_number',
            new_name='transactions_number_day',
        ),
        migrations.AddField(
            model_name='icostatsmodel',
            name='transactions_number_hour',
            field=models.BigIntegerField(default=0, verbose_name='小时总交易次数'),
        ),
    ]
