# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0005_auto_20180508_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='icostatsmodel',
            name='block_time',
            field=models.CharField(default='', max_length=255, verbose_name='平均区块生成时间'),
        ),
    ]
