# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0006_icostatsmodel_block_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='icostatsmodel',
            name='block_count',
            field=models.BigIntegerField(default=0, verbose_name='区块总数'),
        ),
    ]
