# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0007_icostatsmodel_block_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='icostatsmodel',
            name='block_pre_reward',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='当前区块奖励数'),
        ),
        migrations.AddField(
            model_name='icostatsmodel',
            name='difficulty',
            field=models.CharField(default='', max_length=255, verbose_name='难度'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='reward_last_24h',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='24小时区块奖励数'),
        ),
    ]
