# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0008_auto_20180508_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='icostatsmodel',
            name='bitcoins_mined_total',
            field=models.CharField(default='', max_length=255, verbose_name='累计挖出比特币数量'),
        ),
        migrations.AddField(
            model_name='icostatsmodel',
            name='blocks_mined_day',
            field=models.CharField(default='', max_length=255, verbose_name='当天挖出区块'),
        ),
        migrations.AddField(
            model_name='icostatsmodel',
            name='cost_per_transaction',
            field=models.CharField(default='', max_length=255, verbose_name='平均每次交易成本(usd)'),
        ),
        migrations.AddField(
            model_name='icostatsmodel',
            name='hashrate',
            field=models.CharField(default='', max_length=255, verbose_name='算力'),
        ),
        migrations.AddField(
            model_name='icostatsmodel',
            name='mining_pro',
            field=models.CharField(default='', max_length=255, verbose_name='24小时矿工收入'),
        ),
        migrations.AddField(
            model_name='icostatsmodel',
            name='mining_pro_1thash',
            field=models.CharField(default='', max_length=255, verbose_name='1thash/s的算力估计收益'),
        ),
        migrations.AddField(
            model_name='icostatsmodel',
            name='transactions_fees',
            field=models.CharField(default='', max_length=255, verbose_name='交易费用百分比'),
        ),
    ]
