# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0010_auto_20180510_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='icobasicinfomodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='记录创建时间'),
            preserve_default=False,
        ),
    ]
