# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0011_icobasicinfomodel_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='icogithubstatsmodel',
            name='forks',
            field=models.IntegerField(default=0, verbose_name='fork数'),
        ),
    ]
