# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icoinfo', '0012_icogithubstatsmodel_forks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icoexchangesstatsmodel',
            name='circulating_supply',
            field=models.BigIntegerField(default=0, verbose_name='已供应币数(个)'),
        ),
        migrations.AlterField(
            model_name='icoexchangesstatsmodel',
            name='fair_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='公允价格(美元)'),
        ),
        migrations.AlterField(
            model_name='icoexchangesstatsmodel',
            name='market_capitalization',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='市值(美元)'),
        ),
        migrations.AlterField(
            model_name='icoexchangesstatsmodel',
            name='max_supply',
            field=models.BigIntegerField(default=0, verbose_name='总供应币数(个)'),
        ),
        migrations.AlterField(
            model_name='icoexchangesstatsmodel',
            name='total_trade_volume_24h',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='24小时交易所成交总额(美元)'),
        ),
        migrations.AlterField(
            model_name='icoexchangesstatsmodel',
            name='transactions_last_24h',
            field=models.BigIntegerField(default=0, verbose_name='24小时交易量(美元)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='branches',
            field=models.IntegerField(default=0, verbose_name='分支数(个)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='commits_last_week',
            field=models.IntegerField(default=0, verbose_name='上周提交次数(次)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='commits_this_month',
            field=models.IntegerField(default=0, verbose_name='近一个月提交次数(次)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='commits_this_week',
            field=models.IntegerField(default=0, verbose_name='本周提交次数(次)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='forks',
            field=models.IntegerField(default=0, verbose_name='fork数(个)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='issues',
            field=models.IntegerField(default=0, verbose_name='问题数(个)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='projects',
            field=models.TextField(default='', verbose_name='项目库(个)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='stars',
            field=models.IntegerField(default=0, verbose_name='stars数(个)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='stars_incr_week',
            field=models.IntegerField(default=0, verbose_name='本周新增星数(个)'),
        ),
        migrations.AlterField(
            model_name='icogithubstatsmodel',
            name='watchers',
            field=models.IntegerField(default=0, verbose_name='关注数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='active_addresses_last24h',
            field=models.BigIntegerField(default=0, verbose_name='过去24小时活跃地址数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='actual_tps',
            field=models.BigIntegerField(default=0, verbose_name='实际每秒交易量(笔)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='address_richer_than_10000usd',
            field=models.BigIntegerField(default=0, verbose_name='金额超过10000usd钱包地址数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='address_richer_than_1000usd',
            field=models.BigIntegerField(default=0, verbose_name='金额超过1000usd钱包地址数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='address_richer_than_100usd',
            field=models.BigIntegerField(default=0, verbose_name='金额超过100usd钱包地址数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='address_richer_than_1usd',
            field=models.BigIntegerField(default=0, verbose_name='金额超过1usd钱包地址数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='avg_transactions_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='交易价值均值(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='bitcoins_mined_total',
            field=models.CharField(default='', max_length=255, verbose_name='累计挖出比特币数量(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='block_count',
            field=models.BigIntegerField(default=0, verbose_name='区块总数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='block_pre_reward',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='当前区块奖励(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='blocks_avg_perhour',
            field=models.BigIntegerField(default=0, verbose_name='每小时生成区块数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='blocks_last_24h',
            field=models.BigIntegerField(default=0, verbose_name='24小时生成区块数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='blocks_mined_day',
            field=models.CharField(default='', max_length=255, verbose_name='当天挖出区块(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='current_best_transaction_fees',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='最佳交易费用(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='meidan_transactions_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='交易价值中位数(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='mempool_size',
            field=models.BigIntegerField(default=0, verbose_name='未确认交易数量(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='mining_pro',
            field=models.CharField(default='', max_length=255, verbose_name='24小时矿工收入(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='new_addresses_last24h',
            field=models.BigIntegerField(default=0, verbose_name='过去24小时新建地址数(个)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='per_transactions_volume',
            field=models.CharField(default='', max_length=255, verbose_name='24小时矿工收入/交易量'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='reward_last_24h',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='24小时区块奖励数(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='top_100_richest',
            field=models.BigIntegerField(default=0, verbose_name='财富top100地址总金额(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='total_output_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='当日总交易传出量(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='total_transactions_fees',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='当日总交易费(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='transaction_largest100',
            field=models.BigIntegerField(default=0, verbose_name='24小时最大100笔交易总金额(美元)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='transactions_fees',
            field=models.CharField(default='', max_length=255, verbose_name='24小时交易费用百分比'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='transactions_number_day',
            field=models.BigIntegerField(default=0, verbose_name='当日总交易次数(次)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='transactions_number_hour',
            field=models.BigIntegerField(default=0, verbose_name='小时总交易次数(次)'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='wealth_distribution_top10',
            field=models.BigIntegerField(default=0, verbose_name='财富top10地址所占金额百分比'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='wealth_distribution_top100',
            field=models.BigIntegerField(default=0, verbose_name='财富top100地址所占金额百分比'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='wealth_distribution_top1000',
            field=models.BigIntegerField(default=0, verbose_name='财富top1000地址所占金额百分比'),
        ),
        migrations.AlterField(
            model_name='icostatsmodel',
            name='wealth_distribution_top10000',
            field=models.BigIntegerField(default=0, verbose_name='财富top10000地址所占金额百分比'),
        ),
    ]
