# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethereumtransactionmodel',
            old_name='input',
            new_name='input_data',
        ),
        migrations.AlterField(
            model_name='ethereumtransactionreceiptmodel',
            name='contract_address',
            field=models.CharField(default='', max_length=255, verbose_name='合约地址'),
        ),
        migrations.AlterField(
            model_name='ethereumtransactionreceiptmodel',
            name='root',
            field=models.CharField(default='', max_length=255, verbose_name='拜占庭交易状态根'),
        ),
    ]
