# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethereumtransactionreceiptmodel',
            old_name='gas',
            new_name='gas_used',
        ),
    ]
