# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0003_auto_20180428_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumaddressmodel',
            name='balance',
            field=models.CharField(default=0, max_length=255, verbose_name='当前余额'),
        ),
        migrations.AlterField(
            model_name='ethereumblockmodel',
            name='gas_used',
            field=models.CharField(default=0, max_length=255, verbose_name='该区块gas使用总量'),
        ),
        migrations.AlterField(
            model_name='ethereumtransactionmodel',
            name='gas_price',
            field=models.CharField(default=0, max_length=255, verbose_name='gas价格'),
        ),
        migrations.AlterField(
            model_name='ethereumtransactionmodel',
            name='value',
            field=models.CharField(default=0, max_length=255, verbose_name='交易金额Wei'),
        ),
        migrations.AlterField(
            model_name='ethereumtransactionreceiptmodel',
            name='gas_used',
            field=models.CharField(default=0, max_length=255, verbose_name='该交易使用gas量'),
        ),
        migrations.AlterField(
            model_name='ethereumtransactionreceiptmodel',
            name='total_gas',
            field=models.CharField(default=0, max_length=255, verbose_name='区块gas使用总量'),
        ),
    ]
