# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0005_auto_20180428_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumaddressmodel',
            name='received',
            field=models.CharField(default='', max_length=255, verbose_name='总接收数量'),
        ),
        migrations.AlterField(
            model_name='ethereumaddressmodel',
            name='sent',
            field=models.CharField(default='', max_length=255, verbose_name='总支出数量'),
        ),
    ]
