# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=5, default=0, max_digits=40, verbose_name='购买价格')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('exchanges', models.TextField(default='', verbose_name='支持交易所列表')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'verbose_name': 'quant_policy',
                'db_table': 'quant_policy',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
