# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 09:36
from __future__ import unicode_literals

import blockuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blockuser',
            managers=[
                ('objects', blockuser.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='blockuser',
            name='taobao',
            field=models.CharField(blank=True, max_length=30, verbose_name='taobao id'),
        ),
        migrations.AddField(
            model_name='blockuser',
            name='tel',
            field=models.IntegerField(blank=True, default=0, verbose_name='telphone number'),
            preserve_default=False,
        ),
    ]
