# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 04:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuiQiaoPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('huobi', '火币'), ('okex', 'OKEX'), ('fcoin', 'Fcoin')], help_text='请选择一个交易所', max_length=20, verbose_name='交易所')),
                ('accesskey', models.CharField(help_text='请填写您在交易所的api access key', max_length=100, verbose_name='Accesskey')),
                ('secretkey', models.CharField(help_text='请填写您在交易所的api secret key', max_length=100, verbose_name='SecretKey')),
                ('symbol', models.CharField(choices=[('btcusdt', 'BTC/USDT'), ('ethusdt', 'ETH/USDT')], help_text='请填写该交易所的交易对例如BTC/USDT', max_length=20, verbose_name='交易对')),
                ('max_buy_price', models.DecimalField(decimal_places=8, help_text='请填写该交易对的最高买入价格', max_digits=20, verbose_name='最高买入价格')),
                ('min_sell_price', models.DecimalField(decimal_places=8, help_text='请填写该交易对的最低卖出价格', max_digits=20, verbose_name='最低卖出价格')),
                ('percent_balance', models.DecimalField(decimal_places=8, help_text='请填写要使用的资产余额百分比,如0.9就是90%', max_digits=20, verbose_name='资产使用比率')),
                ('start_time', models.DateTimeField(help_text='请填写您的交易策略运行开始时间', verbose_name='开始运行时间')),
                ('end_time', models.DateTimeField(help_text='请填写您的交易策略结束运行时间', verbose_name='结束运行时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='记录更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '对敲策略',
                'db_table': 'duiqiao',
                'abstract': False,
                'managed': True,
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
