# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0002_auto_20180817_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='base_volume',
            field=models.DecimalField(decimal_places=8, default=0, help_text='请填写交易对的币数量,比如BTC/USDT，就是BTC的数量', max_digits=20, verbose_name='base货币数量'),
        ),
    ]
