# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0002_duiqiaopolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='duiqiaopolicy',
            name='status',
            field=models.CharField(blank=True, choices=[('run', '运行中'), ('unstart', '未开始'), ('end', '已结束'), ('stop', '已停止')], default='未开始', help_text='策略运行状态', max_length=10, verbose_name='运行状态'),
        ),
    ]
