# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0003_duiqiaopolicy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='duiqiaopolicy',
            name='operation',
            field=models.IntegerField(blank=True, choices=[(0, '停止运行'), (1, '开启运行')], default=0, help_text='操作', verbose_name='操作'),
        ),
    ]
