# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0003_auto_20180817_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='base_volume',
            field=models.DecimalField(decimal_places=8, default=0, help_text='请填写交易对的币数量比如BTC/USDT就是BTC的数量', max_digits=20, verbose_name='base货币数量'),
        ),
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
