# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0004_auto_20180818_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
