# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0005_auto_20180818_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='base_volume',
            field=models.FloatField(default=0, help_text='请填写交易对的币数量比如BTC/USDT就是BTC的数量', verbose_name='base货币数量'),
        ),
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='exchange',
            field=models.CharField(choices=[('binance', '币安Binance'), ('huobipro', '火币Huobi'), ('hadax', '火币HADAX'), ('okex', 'OKEX'), ('bitmex', 'BitMEX'), ('bitfinex', 'Bitfinex'), ('bitflyer', 'bitFlyer'), ('bittrex', 'Bittrex'), ('bithumb', 'Bithumb'), ('bitmarket', 'bitmarket'), ('bitstamp', 'Bitstamp'), ('bitz', 'Bit-Z'), ('bitlish', 'Bitlish'), ('bitsane', 'Bitsane'), ('bitso', 'Bitso'), ('coinbase', 'coinbase'), ('coinex', 'coinex'), ('coinexchange', 'coinexchange'), ('coinnest', 'coinnest'), ('coinone', 'CoinOne'), ('cointiger', 'CoinTiger'), ('deribit', 'Deribit'), ('gateio', 'Gate.io'), ('gdax', 'GDAX'), ('hitbtc2', 'HitBTC'), ('fcoin', 'FCoin'), ('bcex', 'BCEX'), ('bibox', 'Bibox'), ('bigone', 'BigONE'), ('bitbank', 'bitbank'), ('bitbay', 'BitBay'), ('kraken', 'Kraken'), ('kucoin', 'Kucoin'), ('lbank', 'LBank'), ('poloniex', 'Poloniex'), ('qryptos', 'QRYPTOS'), ('quoinex', 'QUOINEX'), ('tidebit', 'TideBit'), ('uex', 'UEX'), ('vbtc', 'VTBC'), ('wex', 'WEX'), ('zb', 'ZB'), ('yobit', 'YoBit'), ('zaif', 'Zaif')], help_text='请选择一个交易所', max_length=20, verbose_name='交易所'),
        ),
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='max_buy_price',
            field=models.FloatField(default=0, help_text='请填写该交易对的最高买入价格', verbose_name='最高买入价格'),
        ),
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='min_sell_price',
            field=models.FloatField(default=0, help_text='请填写该交易对的最低卖出价格', verbose_name='最低卖出价格'),
        ),
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='symbol',
            field=models.CharField(choices=[('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT')], help_text='请填写该交易所的交易对例如BTC/USDT', max_length=20, verbose_name='交易对'),
        ),
        migrations.AlterField(
            model_name='quantpolicy',
            name='price',
            field=models.FloatField(default=0, verbose_name='购买价格'),
        ),
    ]
