# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0008_quantpolicyorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantpolicyorder',
            name='policy_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quantpolicyorder',
            name='policy_url_add',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quantpolicyorder',
            name='policy_url_list',
            field=models.CharField(default='', max_length=50),
        ),
    ]
