# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockuser', '0010_auto_20180920_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duiqiaopolicy',
            name='base_volume',
            field=models.FloatField(default=0, help_text='请填写交易对的币数量比如BTC/USDT就是BTC的数量', verbose_name='base货币数量'),
        ),
    ]
