# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-08 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjiao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sanjiaopolicy',
            old_name='symbol_1',
            new_name='symbol1',
        ),
        migrations.RenameField(
            model_name='sanjiaopolicy',
            old_name='symbol_2',
            new_name='symbol2',
        ),
    ]
