# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTradeOrderModel',
            fields=[
                ('trade_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Trade Id')),
                ('symbol', models.CharField(default='', max_length=255, verbose_name='交易对')),
                ('price', models.DecimalField(decimal_places=9, default=0, max_digits=40, verbose_name='成交价格')),
                ('amount', models.DecimalField(decimal_places=9, default=0, max_digits=40, verbose_name='成交数量')),
                ('timestamp', models.BigIntegerField(default=0, verbose_name='timestamp')),
                ('side', models.CharField(choices=[(0, '卖出'), (1, '买入')], default=0, max_length=255, verbose_name='成交类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'verbose_name': 'fcoin market trade order',
                'managed': True,
                'db_table': 'market_trade_order',
            },
        ),
    ]
