# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtcAddressModel',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('received', models.BigIntegerField(verbose_name='总接收数量')),
                ('sent', models.BigIntegerField(verbose_name='总支出数量')),
                ('balance', models.BigIntegerField(verbose_name='当前余额')),
                ('tx_count', models.BigIntegerField(verbose_name='交易数量')),
                ('unconfirmed_tx_count', models.BigIntegerField(verbose_name='未确认交易数量')),
                ('unconfirmed_rx_count', models.BigIntegerField(verbose_name='未确认总接收')),
                ('unconfirmed_sent', models.BigIntegerField(verbose_name='未确认总支出')),
                ('unspent_tx_count', models.BigIntegerField(verbose_name='未花费交易数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'db_table': 'btc_address',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'managed': True,
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BtcBlockModel',
            fields=[
                ('height', models.BigIntegerField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('mrkl_root', models.CharField(default='', max_length=255, verbose_name='Merkle Root')),
                ('curr_max_timestamp', models.BigIntegerField(verbose_name='块最大时间戳')),
                ('timestamp', models.BigIntegerField(verbose_name='块时间戳')),
                ('bits', models.BigIntegerField(verbose_name='bits')),
                ('nonce', models.BigIntegerField(verbose_name='随机数')),
                ('hash', models.CharField(max_length=255, verbose_name='快哈希')),
                ('prev_block_hash', models.CharField(max_length=255, verbose_name='前向区块哈希')),
                ('next_block_hash', models.CharField(max_length=255, verbose_name='后向区块哈希')),
                ('size', models.BigIntegerField(verbose_name='区块体积')),
                ('pool_difficulty', models.BigIntegerField(verbose_name='矿池难度')),
                ('difficulty', models.BigIntegerField(verbose_name='块难度')),
                ('tx_count', models.BigIntegerField(verbose_name='交易数量')),
                ('reward_block', models.BigIntegerField(verbose_name='块奖励')),
                ('reward_fees', models.BigIntegerField(verbose_name='块手续费')),
                ('confirmations', models.IntegerField(verbose_name='确认数')),
                ('relayed_by', models.CharField(max_length=255, verbose_name='块播报方')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'db_table': 'btc_block',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'managed': True,
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BtcInputTransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txhash', models.CharField(max_length=255, verbose_name='交易hash')),
                ('prev_address', models.CharField(max_length=255, verbose_name='输入地址')),
                ('prev_position', models.BigIntegerField(verbose_name='前向交易的输出位置')),
                ('prev_value', models.BigIntegerField(verbose_name='前向交易输入金额')),
                ('prev_tx_hash', models.CharField(max_length=255, verbose_name='前向交易哈希')),
                ('script_asm', models.CharField(max_length=255, verbose_name='asm脚本')),
                ('script_hex', models.CharField(max_length=255, verbose_name='hex脚本')),
                ('sequence', models.BigIntegerField(verbose_name='序列')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'db_table': 'btc_input_transaction',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'managed': True,
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BtcOutputTransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txhash', models.CharField(max_length=255, verbose_name='交易hash')),
                ('address', models.CharField(max_length=255, verbose_name='输出地址')),
                ('value', models.BigIntegerField(verbose_name='输出金额')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'db_table': 'btc_output_transaction',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'managed': True,
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BtcStatsModel',
            fields=[
                ('blocks_last_24h', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='24小时生成区块数')),
                ('blocks_avg_perhour', models.BigIntegerField(verbose_name='每小时生成区块数')),
                ('reward_last_24h', models.BigIntegerField(verbose_name='24小时产生奖励数')),
                ('top_100_richest', models.BigIntegerField(verbose_name='前100占有币情况')),
                ('wealth_distribution_top10', models.BigIntegerField(verbose_name='财富10')),
                ('wealth_distribution_top100', models.BigIntegerField(verbose_name='财富100')),
                ('wealth_distribution_top1000', models.BigIntegerField(verbose_name='财富1000')),
                ('wealth_distribution_top10000', models.BigIntegerField(verbose_name='财富10000')),
                ('address_richer_than_1usd', models.BigIntegerField(verbose_name='金额超过1usd地址')),
                ('address_richer_than_100usd', models.BigIntegerField(verbose_name='金额超过100usd地址')),
                ('address_richer_than_1000usd', models.BigIntegerField(verbose_name='金额超过1000usd地址')),
                ('address_richer_than_10000usd', models.BigIntegerField(verbose_name='金额超过10000usd地址')),
                ('active_addresses_last24h', models.BigIntegerField(verbose_name='24小时活跃地址数')),
                ('transaction_largest100', models.BigIntegerField(verbose_name='24小时最大100笔交易')),
                ('address_numbers', models.BigIntegerField(verbose_name='持币地址数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'db_table': 'btc_stats',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'managed': True,
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BtcTransactionModel',
            fields=[
                ('txhash', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_height', models.BigIntegerField(verbose_name='所在块高度')),
                ('block_time', models.BigIntegerField(verbose_name='所在块时间')),
                ('fee', models.BigIntegerField(verbose_name='交易手续费')),
                ('inputs_count', models.BigIntegerField(verbose_name='输入数量')),
                ('inputs_value', models.BigIntegerField(verbose_name='输入金额')),
                ('is_coinbase', models.BooleanField(verbose_name='是否为coinbase交易')),
                ('lock_time', models.BigIntegerField(verbose_name='锁定时间')),
                ('outputs_count', models.BigIntegerField(verbose_name='输出数量')),
                ('outputs_value', models.BigIntegerField(verbose_name='输出金额')),
                ('size', models.BigIntegerField(verbose_name='交易体积')),
                ('version', models.BigIntegerField(verbose_name='交易版本号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'db_table': 'btc_transaction',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'managed': True,
                'abstract': False,
            },
        ),
    ]
