# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcblockmodel',
            name='weight',
            field=models.BigIntegerField(default=0, verbose_name='区块重量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='bits',
            field=models.CharField(max_length=255, verbose_name='bits'),
        ),
    ]
