# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0002_btctransactionmodel_confirmations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='script_asm',
            field=models.TextField(default='', verbose_name='asm脚本'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='script_hex',
            field=models.TextField(default='', verbose_name='hex脚本'),
        ),
    ]
