# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btc', '0002_auto_20180425_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcstatsmodel',
            name='total',
            field=models.BigIntegerField(default=0, verbose_name='币总量'),
        ),
        migrations.AlterField(
            model_name='btcaddressmodel',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='当前余额'),
        ),
        migrations.AlterField(
            model_name='btcaddressmodel',
            name='received',
            field=models.BigIntegerField(default=0, verbose_name='总接收数量'),
        ),
        migrations.AlterField(
            model_name='btcaddressmodel',
            name='sent',
            field=models.BigIntegerField(default=0, verbose_name='总支出数量'),
        ),
        migrations.AlterField(
            model_name='btcaddressmodel',
            name='tx_count',
            field=models.BigIntegerField(default=0, verbose_name='交易数量'),
        ),
        migrations.AlterField(
            model_name='btcaddressmodel',
            name='unconfirmed_rx_count',
            field=models.BigIntegerField(default=0, verbose_name='未确认总接收'),
        ),
        migrations.AlterField(
            model_name='btcaddressmodel',
            name='unconfirmed_sent',
            field=models.BigIntegerField(default=0, verbose_name='未确认总支出'),
        ),
        migrations.AlterField(
            model_name='btcaddressmodel',
            name='unconfirmed_tx_count',
            field=models.BigIntegerField(default=0, verbose_name='未确认交易数量'),
        ),
        migrations.AlterField(
            model_name='btcaddressmodel',
            name='unspent_tx_count',
            field=models.BigIntegerField(default=0, verbose_name='未花费交易数量'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='bits',
            field=models.CharField(default='', max_length=255, verbose_name='bits'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='confirmations',
            field=models.IntegerField(default=0, verbose_name='确认数'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='curr_max_timestamp',
            field=models.BigIntegerField(default=0, verbose_name='块最大时间戳'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='difficulty',
            field=models.BigIntegerField(default=0, verbose_name='块难度'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='hash',
            field=models.CharField(default='', max_length=255, verbose_name='快哈希'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='next_block_hash',
            field=models.CharField(default='', max_length=255, verbose_name='后向区块哈希'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='nonce',
            field=models.BigIntegerField(default=0, verbose_name='随机数'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='pool_difficulty',
            field=models.BigIntegerField(default=0, verbose_name='矿池难度'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='prev_block_hash',
            field=models.CharField(default='', max_length=255, verbose_name='前向区块哈希'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='relayed_by',
            field=models.CharField(default='', max_length=255, verbose_name='块播报方'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='reward_block',
            field=models.BigIntegerField(default=0, verbose_name='块奖励'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='reward_fees',
            field=models.BigIntegerField(default=0, verbose_name='块手续费'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='区块体积'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='timestamp',
            field=models.BigIntegerField(default=0, verbose_name='块时间戳'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='tx_count',
            field=models.BigIntegerField(default=0, verbose_name='交易数量'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='version',
            field=models.IntegerField(default=0, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='btcblockmodel',
            name='weight',
            field=models.BigIntegerField(default=0, verbose_name='区块重量'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='prev_address',
            field=models.CharField(default='', max_length=255, verbose_name='输入地址'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='prev_position',
            field=models.BigIntegerField(default=0, verbose_name='前向交易的输出位置'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='prev_tx_hash',
            field=models.CharField(default='', max_length=255, verbose_name='前向交易哈希'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='prev_value',
            field=models.BigIntegerField(default=0, verbose_name='前向交易输入金额'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='script_asm',
            field=models.CharField(default='', max_length=255, verbose_name='asm脚本'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='script_hex',
            field=models.CharField(default='', max_length=255, verbose_name='hex脚本'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='sequence',
            field=models.BigIntegerField(default=0, verbose_name='序列'),
        ),
        migrations.AlterField(
            model_name='btcinputtransactionmodel',
            name='txhash',
            field=models.CharField(default='', max_length=255, verbose_name='交易hash'),
        ),
        migrations.AlterField(
            model_name='btcoutputtransactionmodel',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='输出地址'),
        ),
        migrations.AlterField(
            model_name='btcoutputtransactionmodel',
            name='txhash',
            field=models.CharField(default='', max_length=255, verbose_name='交易hash'),
        ),
        migrations.AlterField(
            model_name='btcoutputtransactionmodel',
            name='value',
            field=models.BigIntegerField(default=0, verbose_name='输出金额'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='active_addresses_last24h',
            field=models.BigIntegerField(default=0, verbose_name='24小时活跃地址数'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='address_numbers',
            field=models.BigIntegerField(default=0, verbose_name='持币地址数'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='address_richer_than_10000usd',
            field=models.BigIntegerField(default=0, verbose_name='金额超过10000usd地址'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='address_richer_than_1000usd',
            field=models.BigIntegerField(default=0, verbose_name='金额超过1000usd地址'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='address_richer_than_100usd',
            field=models.BigIntegerField(default=0, verbose_name='金额超过100usd地址'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='address_richer_than_1usd',
            field=models.BigIntegerField(default=0, verbose_name='金额超过1usd地址'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='blocks_avg_perhour',
            field=models.BigIntegerField(default=0, verbose_name='每小时生成区块数'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='reward_last_24h',
            field=models.BigIntegerField(default=0, verbose_name='24小时产生奖励数'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='top_100_richest',
            field=models.BigIntegerField(default=0, verbose_name='前100占有币情况'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='transaction_largest100',
            field=models.BigIntegerField(default=0, verbose_name='24小时最大100笔交易'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='wealth_distribution_top10',
            field=models.BigIntegerField(default=0, verbose_name='财富10'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='wealth_distribution_top100',
            field=models.BigIntegerField(default=0, verbose_name='财富100'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='wealth_distribution_top1000',
            field=models.BigIntegerField(default=0, verbose_name='财富1000'),
        ),
        migrations.AlterField(
            model_name='btcstatsmodel',
            name='wealth_distribution_top10000',
            field=models.BigIntegerField(default=0, verbose_name='财富10000'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='block_height',
            field=models.BigIntegerField(default=0, verbose_name='所在块高度'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='block_time',
            field=models.BigIntegerField(default=0, verbose_name='所在块时间'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='fee',
            field=models.BigIntegerField(default=0, verbose_name='交易手续费'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='inputs_count',
            field=models.BigIntegerField(default=0, verbose_name='输入数量'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='inputs_value',
            field=models.BigIntegerField(default=0, verbose_name='输入金额'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='is_coinbase',
            field=models.BooleanField(default=0, verbose_name='是否为coinbase交易'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='lock_time',
            field=models.BigIntegerField(default=0, verbose_name='锁定时间'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='outputs_count',
            field=models.BigIntegerField(default=0, verbose_name='输出数量'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='outputs_value',
            field=models.BigIntegerField(default=0, verbose_name='输出金额'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='交易体积'),
        ),
        migrations.AlterField(
            model_name='btctransactionmodel',
            name='version',
            field=models.BigIntegerField(default=0, verbose_name='交易版本号'),
        ),
    ]
